'use strict';function u(f,c,e,g,t){f.c.da(f.G,c,e,g,t)}function x(f,c,e,g){f.c.m?u(f,c,e,g):f.c.yb()._OnMessageFromDOM({type:"event",component:f.G,handler:c,dispatchOpts:g||null,data:e,responseId:null})}function z(f,c,e){f.c.a(f.G,c,e)}function B(f,c){for(const [e,g]of c)z(f,e,g)}window.aa=class{constructor(f,c){this.c=f;this.G=c;this.Xa=!1;this.lc=()=>this.Ha()}Ca(){}Ha(){}};
window.lb=class{constructor(f,c){this.Va=f;this.ec=c;this.A=-1;this.W=-Infinity;this.mc=()=>{this.A=-1;this.W=Date.now();this.H=!0;this.Va();this.H=!1};this.Wa=this.H=!1}};"use strict";function C(f,c){const e=c.elementId,g=f.N(e,c);f.f.set(e,g);c.isVisible||(g.style.display="none");g.addEventListener("focus",()=>{D(f,"elem-focused",e)});g.addEventListener("blur",()=>{D(f,"elem-blurred",e)});f.F&&document.body.appendChild(g)}
function E(f,c,e){z(f,c,g=>{const t=f.f.get(g.elementId);return e(t,g)})}function D(f,c,e,g){g||(g={});g.elementId=e;u(f,c,g)}function F(f,c,e,g){g||(g={});g.elementId=e;x(f,c,g)}
window.$=class extends self.aa{constructor(f,c){super(f,c);this.f=new Map;this.F=!0;B(this,[["create",e=>C(this,e)],["destroy",e=>{{e=e.elementId;const g=this.f.get(e);this.Fa(g);this.F&&g.parentElement.removeChild(g);this.f.delete(e)}}],["set-visible",e=>{this.F&&(this.f.get(e.elementId).style.display=e.isVisible?"":"none")}],["update-position",e=>{if(this.F){var g=this.f.get(e.elementId);g.style.left=e.left+"px";g.style.top=e.top+"px";g.style.width=e.width+"px";g.style.height=e.height+"px";e=e.fontSize;
null!==e&&(g.style.fontSize=e+"em")}}],["update-state",e=>{{const g=this.f.get(e.elementId);this.s(g,e)}}],["focus",e=>this.na(e)],["set-css-style",e=>{this.f.get(e.elementId).style[e.prop]=e.val}],["set-attribute",e=>{this.f.get(e.elementId).setAttribute(e.name,e.val)}],["remove-attribute",e=>{this.f.get(e.elementId).removeAttribute(e.name)}]]);E(this,"get-element",e=>e)}N(){throw Error("required override");}Fa(){}s(){throw Error("required override");}na(f){const c=this.f.get(f.elementId);f.focus?
c.focus():c.blur()}};"use strict";
{var G=function(p){return m.has(p)},H=function(p){return new Promise((b,h)=>{const k=new FileReader;k.onload=n=>b(n.target.result);k.onerror=n=>h(n);k.readAsArrayBuffer(p)})},I=async function(p){p=await H(p);return(new TextDecoder("utf-8")).decode(p)},J=function(p){if(p.pc){const b=document.createElement("script");b.async=!1;b.textContent=p.sc;document.head.appendChild(b)}else return new Promise((b,h)=>{const k=document.createElement("script");k.onload=b;k.onerror=h;k.async=!1;k.src=p;document.head.appendChild(k)})};
const f=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let c=new Audio;const e={"audio/webm; codecs=opus":!!c.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!c.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!c.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!c.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!c.canPlayType("audio/mp4"),"audio/mpeg":!!c.canPlayType("audio/mpeg")};c=null;const g=[];let t=0;window.RealFile=
window.File;const r=[],v=new Map,a=new Map;let d=0;const l=[];self.Dc=function(p){if("function"!==typeof p)throw Error("runOnStartup called without a function");l.push(p)};const m=new Set(["cordova","playable-ad","instant-games"]);window.o=class p{constructor(b){this.m=b.uc;this.J=null;this.g="";this.za=b.rc;this.M={};this.ua=this.bb=null;this.V=[];this.I=this.h=this.ya=null;this.u=-1;this.jc=()=>this.Rb();this.xa=[];this.b=b.cb;G(this.b)&&this.m&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is disabled in WebViews due to crbug.com/923007. Reverting to DOM mode."),
this.m=!1);this.ab=!1;this.X=this.i=null;"html5"!==this.b&&"playable-ad"!==this.b||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");this.a("runtime","cordova-fetch-local-file",h=>this.Fb(h));this.a("runtime","create-job-worker",()=>this.Gb());"cordova"===this.b?document.addEventListener("deviceready",()=>this.Ma(b)):this.Ma(b)}ca(){return f&&"cordova"===
this.b}O(){return f&&G(this.b)||navigator.standalone}async Ma(b){if("playable-ad"===this.b){this.i=self.c3_base64files;this.X={};await this.tb();for(let k=0,n=b.B.length;k<n;++k){var h=b.B[k].toLowerCase();this.X.hasOwnProperty(h)?b.B[k]={pc:!0,sc:this.X[h]}:this.i.hasOwnProperty(h)&&(b.B[k]=URL.createObjectURL(this.i[h]))}}b.nc?this.g=b.nc:(h=location.origin,this.g=("null"===h?"file:///":h)+location.pathname,h=this.g.lastIndexOf("/"),-1!==h&&(this.g=this.g.substr(0,h+1)));if(b.wc)for(const [k,n]of Object.entries(b.wc))this.M[k]=
URL.createObjectURL(n);h=new MessageChannel;this.J=h.port1;this.J.onmessage=k=>this._OnMessageFromRuntime(k.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(k=>this.Ob(k));this.I=new self.jb(this);await this.I.ib();this.Ga();"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();await this.bc();this.m?await this.Bb(b,h.port2):await this.Ab(b,h.port2)}ga(b){return this.M.hasOwnProperty(b)?
this.M[b]:b.endsWith("/workermain.js")&&this.M.hasOwnProperty("workermain.js")?this.M["workermain.js"]:"playable-ad"===this.b&&this.i.hasOwnProperty(b.toLowerCase())?URL.createObjectURL(this.i[b.toLowerCase()]):b}async Z(b,h,k){if(b.startsWith("blob:"))return new Worker(b,k);if(this.ca()&&"file:"===location.protocol)return b=await this.Ea(this.za+b),new Worker(URL.createObjectURL(new Blob([b],{type:"application/javascript"})),k);b=new URL(b,h);if(location.origin!==b.origin){b=await fetch(b);if(!b.ok)throw Error("failed to fetch worker script");
b=await b.blob();return new Worker(URL.createObjectURL(b),k)}return new Worker(b,k)}Ga(){if(this.O()){const b=document.documentElement.style,h=document.body.style,k=window.innerWidth<window.innerHeight,n=k?window.screen.width:window.screen.height;h.height=b.height=(k?window.screen.height:window.screen.width)+"px";h.width=b.width=n+"px"}}Ka(b){return{baseUrl:this.g,windowInnerWidth:window.innerWidth,windowInnerHeight:window.innerHeight,devicePixelRatio:window.devicePixelRatio,isFullscreen:p.ba(),projectData:b.Cc,
previewImageBlobs:window.cr_previewImageBlobs||this.i,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,exportType:b.cb,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Bc,jobScheduler:this.I.gb(),supportedAudioFormats:e,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.za+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.za+"opus.wasm.wasm",isiOSCordova:this.ca(),isiOSWebView:this.O(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async Bb(b,h){var k=
this.ga(b.vc);this.bb=await this.Z(k,this.g,{name:"Runtime"});this.h=document.createElement("canvas");this.h.style.display="none";k=this.h.transferControlToOffscreen();document.body.appendChild(this.h);window.c3canvas=this.h;this.bb.postMessage(Object.assign(this.Ka(b),{type:"init-runtime",isInWorker:!0,messagePort:h,canvas:k,workerDependencyScripts:b.Ba||[],engineScripts:b.B,projectScripts:window.Ac,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[h,k,...this.I.hb()]);this.V=r.map(n=>new n(this));
this.Ja();self.c3_callFunction=(n,q)=>this.ya.Cb(n,q);"preview"===this.b&&(self.goToLastErrorScript=()=>this.da("runtime","go-to-last-error-script"))}async Ab(b,h){this.h=document.createElement("canvas");this.h.style.display="none";document.body.appendChild(this.h);window.c3canvas=this.h;this.V=r.map(n=>new n(this));this.Ja();const k=b.B.map(n=>"string"===typeof n?(new URL(n,this.g)).toString():n);Array.isArray(b.Ba)&&k.unshift(...b.Ba);await Promise.all(k.map(n=>J(n)));if(b.eb&&0<b.eb.length){const n=
self.C3_ProjectScriptsStatus;try{if(await Promise.all(b.eb.map(q=>J(q[1]))),Object.values(n).some(q=>!q)){self.setTimeout(()=>this.Sa(n),100);return}}catch(q){console.error("[Preview] Error loading project scripts: ",q);self.setTimeout(()=>this.Sa(n),100);return}}"preview"===this.b&&"object"!==typeof self.xc.yc?(console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):
(b=Object.assign(this.Ka(b),{isInWorker:!1,messagePort:h,canvas:this.h,runOnStartupFunctions:l}),this.ua=self.C3_CreateRuntime(b),await self.C3_InitRuntime(this.ua,b))}Sa(b){b=`Failed to load project script '${Object.entries(b).filter(h=>!h[1]).map(h=>h[0])[0]}'. Check all your JavaScript code has valid syntax.`;console.error("[Preview] "+b);alert(b)}async Gb(){const b=await this.I.Ia();return{outputPort:b,transferables:[b]}}yb(){if(this.m)throw Error("not available in worker mode");return this.ua}da(b,
h,k,n,q){this.J.postMessage({type:"event",component:b,handler:h,dispatchOpts:n||null,data:k,responseId:null},this.ab?void 0:q)}kb(b,h){const k=d++,n=new Promise((q,y)=>{a.set(k,{resolve:q,reject:y})});this.J.postMessage({type:"event",component:b,handler:"js-invoke-function",dispatchOpts:null,data:h,responseId:k},void 0);return n}["_OnMessageFromRuntime"](b){const h=b.type;if("event"===h)return this.Lb(b);if("result"===h)this.Ub(b);else if("runtime-ready"===h)this.Vb();else if("alert"===h)alert(b.message);
else throw Error(`unknown message '${h}'`);}Lb(b){const h=b.component,k=b.handler,n=b.data,q=b.responseId;if(b=v.get(h))if(b=b.get(k)){var y=null;try{y=b(n)}catch(w){console.error(`Exception in '${h}' handler '${k}':`,w);null!==q&&this.T(q,!1,""+w);return}if(null===q)return y;y&&y.then?y.then(w=>this.T(q,!0,w)).catch(w=>{console.error(`Rejection from '${h}' handler '${k}':`,w);this.T(q,!1,""+w)}):this.T(q,!0,y)}else console.warn(`[DOM] No handler '${k}' for component '${h}'`);else console.warn(`[DOM] No event handlers for component '${h}'`)}T(b,
h,k){let n;k&&k.transferables&&(n=k.transferables);this.J.postMessage({type:"result",responseId:b,isOk:h,result:k},n)}Ub(b){const h=b.responseId,k=b.isOk;b=b.result;const n=a.get(h);k?n.resolve(b):n.reject(b);a.delete(h)}a(b,h,k){let n=v.get(b);n||(n=new Map,v.set(b,n));if(n.has(h))throw Error(`[DOM] Component '${b}' already has handler '${h}'`);n.set(h,k)}static C(b){if(r.includes(b))throw Error("DOM handler already added");r.push(b)}Ja(){for(const b of this.V)if("runtime"===b.G){this.ya=b;return}throw Error("cannot find runtime DOM handler");
}Ob(b){this.da("debugger","message",b)}Vb(){for(const b of this.V)b.Ca()}static ba(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement)}nb(b){this.xa.push(b);this.qa()}qa(){-1===this.u&&this.xa.length&&(this.u=requestAnimationFrame(this.jc))}rb(){-1!==this.u&&(cancelAnimationFrame(this.u),this.u=-1)}Rb(){this.u=-1;for(const b of this.xa)b();this.qa()}pa(){this.ya.pa()}async Fb(b){const h=b.filename;switch(b.as){case "text":return await this.fb(h);
case "buffer":return await this.Ea(h);default:throw Error("unsupported type");}}La(){const b=window.cordova&&window.cordova.plugins&&window.cordova.plugins.permissions;if("object"!==typeof b)throw Error("Permission API is not loaded");return b}Oa(b,h){b=b[h];if("string"!==typeof b)throw Error("Invalid permission name");return b}zb(b){const h=this.La();return new Promise((k,n)=>h.checkPermission(this.Oa(h,b),q=>k(!!q.hasPermission),n))}$b(b){const h=this.La();return new Promise((k,n)=>h.requestPermission(this.Oa(h,
b),q=>k(!!q.hasPermission),n))}async mb(b){if("cordova"!==this.b||this.ca())return!0;for(const h of b)if(!await this.zb(h)&&!1===await this.$b(h))return!1;return!0}async ea(...b){if(!1===await this.mb(b))throw Error("Permission not granted");}Da(b){const h=window.cordova.file.applicationDirectory+"www/"+b.toLowerCase();return new Promise((k,n)=>{window.resolveLocalFileSystemURL(h,q=>{q.file(k,n)},n)})}async fb(b){b=await this.Da(b);return await I(b)}fa(){if(g.length&&!(8<=t)){t++;var b=g.shift();
this.ub(b.filename,b.tc,b.oc)}}Ea(b){return new Promise((h,k)=>{g.push({filename:b,tc:n=>{t--;this.fa();h(n)},oc:n=>{t--;this.fa();k(n)}});this.fa()})}async ub(b,h,k){try{const n=await this.Da(b),q=await H(n);h(q)}catch(n){k(n)}}async tb(){const b=[];for(const [h,k]of Object.entries(this.i))b.push(this.sb(h,k));await Promise.all(b)}async sb(b,h){if("object"===typeof h)this.i[b]=new Blob([h.str],{type:h.type}),this.X[b]=h.str;else{let k=await this.xb(h);k||(k=this.vb(h));this.i[b]=k}}async xb(b){try{return await (await fetch(b)).blob()}catch(h){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",
h),null}}vb(b){b=this.Zb(b);return this.qb(b.data,b.qc)}Zb(b){var h=b.indexOf(",");if(0>h)throw new URIError("expected comma in data: uri");var k=b.substring(h+1);h=b.substring(5,h).split(";");b=h[0]||"";const n=h[2];k="base64"===h[1]||"base64"===n?atob(k):decodeURIComponent(k);return{qc:b,data:k}}qb(b,h){var k=b.length;let n=k>>2,q=new Uint8Array(k),y=new Uint32Array(q.buffer,0,n),w,A;for(A=w=0;w<n;++w)y[w]=b.charCodeAt(A++)|b.charCodeAt(A++)<<8|b.charCodeAt(A++)<<16|b.charCodeAt(A++)<<24;for(k&=
3;k--;)q[A]=b.charCodeAt(A),++A;return new Blob([q],{type:h})}bc(){let b=null;const h=new Promise(q=>b=q),k=new ArrayBuffer(1),n=new MessageChannel;n.port2.onmessage=q=>{q.data&&q.data.arrayBuffer||(this.ab=!0,console.warn("MessageChannel transfers determined to be broken. Disabling transferables."));b()};n.port1.postMessage({arrayBuffer:k},[k]);return h}}}"use strict";
{var L=function(){const a=document.activeElement;if(!a)return!1;const d=a.tagName.toLowerCase(),l=new Set("email number password search tel text url".split(" "));return"textarea"===d?!0:"input"===d?l.has(a.type.toLowerCase()||"text"):K(a)},M=function(){try{return window.parent&&window.parent.document.hasFocus()}catch(a){return!1}},N=function(a){(a.metaKey||a.ctrlKey)&&a.preventDefault()},O=function(a){r.has(a.target.tagName.toLowerCase())&&a.preventDefault()},K=function(a){do{if(a.parentNode&&a.hasAttribute("contenteditable"))return!0;
a=a.parentNode}while(a);return!1},R=async function(a,d,l){if(!/firefox/i.test(navigator.userAgent))return await P(a);var m=await Q(a);m=(new DOMParser).parseFromString(m,"image/svg+xml");const p=m.documentElement;if(p.hasAttribute("width")&&p.hasAttribute("height")){const b=p.getAttribute("width"),h=p.getAttribute("height");if(!b.includes("%")&&!h.includes("%"))return await P(a)}p.setAttribute("width",d+"px");p.setAttribute("height",l+"px");m=(new XMLSerializer).serializeToString(m);a=new Blob([m],
{type:"image/svg+xml"});return await P(a)},Q=function(a){return new Promise((d,l)=>{let m=new FileReader;m.onload=p=>d(p.target.result);m.onerror=p=>l(p);m.readAsText(a)})},P=async function(a){a=URL.createObjectURL(a);try{return await S(a)}finally{URL.revokeObjectURL(a)}},S=function(a){return new Promise((d,l)=>{const m=new Image;m.onload=()=>d(m);m.onerror=p=>l(p);m.src=a})},T=function(a){return new Promise((d,l)=>{const m=document.createElement("link");m.onload=()=>d(m);m.onerror=p=>l(p);m.rel=
"stylesheet";m.href=a;document.head.appendChild(m)})},U=function(a){return a.sourceCapabilities&&a.sourceCapabilities.firesTouchEvents||a.originalEvent&&a.originalEvent.sourceCapabilities&&a.originalEvent.sourceCapabilities.firesTouchEvents};const f=self.o,c=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),e={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},g={dispatchUserScriptEvent:!0},t={dispatchRuntimeEvent:!0},r=new Set(["canvas","body","html"]);self.C3_GetSvgImageSize=async function(a){a=
await P(a);if(0<a.width&&0<a.height)return[a.width,a.height];{a.style.position="absolute";a.style.left="0px";a.style.top="0px";a.style.visibility="hidden";document.body.appendChild(a);const d=a.getBoundingClientRect();document.body.removeChild(a);return[d.width,d.height]}};self.C3_RasterSvgImageBlob=async function(a,d,l,m,p){a=await R(a,d,l);const b=document.createElement("canvas");b.width=m;b.height=p;b.getContext("2d").drawImage(a,0,0,d,l);return b};let v=!1;document.addEventListener("pause",()=>
v=!0);document.addEventListener("resume",()=>v=!1);f.C(class extends self.aa{constructor(a){super(a,"runtime");this.Ya=!0;this.v=-1;this.Aa="any";this.Ta=this.Ua=!1;this.ta=this.L=this.j=null;a.a("canvas","update-size",m=>this.Xb(m));a.a("runtime","invoke-download",m=>this.Nb(m));a.a("runtime","raster-svg-image",m=>this.Sb(m));a.a("runtime","get-svg-image-size",m=>this.Mb(m));a.a("runtime","set-target-orientation",m=>this.Wb(m));a.a("runtime","register-sw",()=>this.Tb());a.a("runtime","post-to-debugger",
m=>this.Qa(m));a.a("runtime","go-to-script",m=>this.Qa(m));a.a("runtime","before-start-ticking",()=>this.Eb());a.a("runtime","debug-highlight",m=>this.Hb(m));a.a("runtime","enable-device-orientation",()=>this.pb());a.a("runtime","enable-device-motion",()=>this.ob());a.a("runtime","add-stylesheet",m=>this.Db(m));a.a("runtime","alert",m=>this.ia(m));const d=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",m=>{const p=m.target;d.has(p.tagName.toLowerCase())||K(p)||m.preventDefault()});
const l=a.h;window.addEventListener("selectstart",O);window.addEventListener("gesturehold",O);l.addEventListener("selectstart",O);l.addEventListener("gesturehold",O);window.addEventListener("touchstart",O,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",O,{passive:!1}),l.addEventListener("pointerdown",O)):l.addEventListener("touchstart",O);this.K=0;window.addEventListener("mousedown",m=>{1===m.button&&m.preventDefault()});window.addEventListener("mousewheel",
N,{passive:!1});window.addEventListener("wheel",N,{passive:!1});window.addEventListener("resize",()=>this.Yb());a.O()&&window.addEventListener("focusout",()=>{L()||(document.scrollingElement.scrollTop=0)});this.va=new Set;this.ic=new WeakSet;this.fc=!1}Eb(){"cordova"===this.c.b?(document.addEventListener("pause",()=>this.oa(!0)),document.addEventListener("resume",()=>this.oa(!1))):document.addEventListener("visibilitychange",()=>this.oa(document.hidden));return{isSuspended:!(!document.hidden&&!v)}}Ca(){window.addEventListener("focus",
()=>this.U("window-focus"));window.addEventListener("blur",()=>{this.U("window-blur",{parentHasFocus:M()});this.K=0});window.addEventListener("fullscreenchange",()=>this.ja());window.addEventListener("webkitfullscreenchange",()=>this.ja());window.addEventListener("mozfullscreenchange",()=>this.ja());window.addEventListener("fullscreenerror",d=>this.ka(d));window.addEventListener("webkitfullscreenerror",d=>this.ka(d));window.addEventListener("mozfullscreenerror",d=>this.ka(d));window.addEventListener("keydown",
d=>this.Pa("keydown",d));window.addEventListener("keyup",d=>this.Pa("keyup",d));window.addEventListener("dblclick",d=>this.la("dblclick",d,e));window.addEventListener("wheel",d=>this.Pb(d));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",d=>{this.ha(d);this.D("pointerdown",d)}),this.c.m&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.L=new self.lb(()=>this.wb(),5),this.L.Wa=!0,window.addEventListener("pointerrawupdate",d=>this.Qb(d))):window.addEventListener("pointermove",
d=>this.D("pointermove",d)),window.addEventListener("pointerup",d=>this.D("pointerup",d)),window.addEventListener("pointercancel",d=>this.D("pointercancel",d))):(window.addEventListener("mousedown",d=>{this.ha(d);this.ma("pointerdown",d)}),window.addEventListener("mousemove",d=>this.ma("pointermove",d)),window.addEventListener("mouseup",d=>this.ma("pointerup",d)),window.addEventListener("touchstart",d=>{this.ha(d);this.S("pointerdown",d)}),window.addEventListener("touchmove",d=>this.S("pointermove",
d)),window.addEventListener("touchend",d=>this.S("pointerup",d)),window.addEventListener("touchcancel",d=>this.S("pointercancel",d)));const a=()=>this.pa();window.addEventListener("pointerup",a,!0);window.addEventListener("touchend",a,!0);window.addEventListener("click",a,!0);window.addEventListener("keydown",a,!0);window.addEventListener("gamepadconnected",a,!0)}U(a,d){u(this,a,d||null,t)}R(){return Math.max(window.innerWidth,1)}P(){return Math.max(window.innerHeight,1)}Yb(){const a=this.R(),d=this.P();
this.U("window-resize",{innerWidth:a,innerHeight:d,devicePixelRatio:window.devicePixelRatio});this.c.O()&&(-1!==this.v&&clearTimeout(this.v),this.Ra(a,d,0))}ac(a,d,l){-1!==this.v&&clearTimeout(this.v);this.v=setTimeout(()=>this.Ra(a,d,l),48)}Ra(a,d,l){const m=this.R(),p=this.P();this.v=-1;m!=a||p!=d?this.U("window-resize",{innerWidth:m,innerHeight:p,devicePixelRatio:window.devicePixelRatio}):10>l&&this.ac(m,p,l+1)}Wb(a){this.Aa=a.targetOrientation}cc(){const a=this.Aa;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(a).catch(d=>
console.warn("[Construct 3] Failed to lock orientation: ",d));else try{let d=!1;screen.lockOrientation?d=screen.lockOrientation(a):screen.webkitLockOrientation?d=screen.webkitLockOrientation(a):screen.mozLockOrientation?d=screen.mozLockOrientation(a):screen.msLockOrientation&&(d=screen.msLockOrientation(a));d||console.warn("[Construct 3] Failed to lock orientation")}catch(d){console.warn("[Construct 3] Failed to lock orientation: ",d)}}ja(){const a=f.ba();a&&"any"!==this.Aa&&this.cc();u(this,"fullscreenchange",
{isFullscreen:a,innerWidth:this.R(),innerHeight:this.P()})}ka(a){console.warn("[Construct 3] Fullscreen request failed: ",a);u(this,"fullscreenerror",{isFullscreen:f.ba(),innerWidth:this.R(),innerHeight:this.P()})}oa(a){a?this.c.rb():this.c.qa();u(this,"visibilitychange",{hidden:a})}Pa(a,d){"Backspace"===d.key&&O(d);const l=c.get(d.code)||d.code;x(this,a,{code:l,key:d.key,which:d.which,repeat:d.repeat,altKey:d.altKey,ctrlKey:d.ctrlKey,metaKey:d.metaKey,shiftKey:d.shiftKey,timeStamp:d.timeStamp},e)}Pb(a){u(this,
"wheel",{clientX:a.clientX,clientY:a.clientY,pageX:a.pageX,pageY:a.pageY,deltaX:a.deltaX,deltaY:a.deltaY,deltaZ:a.deltaZ,deltaMode:a.deltaMode,timeStamp:a.timeStamp},e)}la(a,d,l){U(d)||x(this,a,{button:d.button,buttons:d.buttons,clientX:d.clientX,clientY:d.clientY,pageX:d.pageX,pageY:d.pageY,timeStamp:d.timeStamp},l)}ma(a,d){if(!U(d)){var l=this.K;"pointerdown"===a&&0!==l?a="pointermove":"pointerup"===a&&0!==d.buttons&&(a="pointermove");x(this,a,{pointerId:1,pointerType:"mouse",button:d.button,buttons:d.buttons,
lastButtons:l,clientX:d.clientX,clientY:d.clientY,pageX:d.pageX,pageY:d.pageY,width:0,height:0,pressure:0,tangentialPressure:0,tiltX:0,tiltY:0,twist:0,timeStamp:d.timeStamp},e);this.K=d.buttons;this.la(d.type,d,g)}}D(a,d){if(this.L&&"pointermove"!==a){var l=this.L;l.H||(-1!==l.A&&(self.clearTimeout(l.A),l.A=-1),l.W=Date.now())}l=0;"mouse"===d.pointerType&&(l=this.K);x(this,a,{pointerId:d.pointerId,pointerType:d.pointerType,button:d.button,buttons:d.buttons,lastButtons:l,clientX:d.clientX,clientY:d.clientY,
pageX:d.pageX,pageY:d.pageY,width:d.width||0,height:d.height||0,pressure:d.pressure||0,tangentialPressure:d.tangentialPressure||0,tiltX:d.tiltX||0,tiltY:d.tiltY||0,twist:d.twist||0,timeStamp:d.timeStamp},e);"mouse"===d.pointerType&&(l="mousemove","pointerdown"===a?l="mousedown":"pointerup"===a&&(l="pointerup"),this.la(l,d,g),this.K=d.buttons)}Qb(a){this.ta=a;a=this.L;if(-1===a.A){var d=Date.now(),l=d-a.W,m=a.ec;l>=m&&a.Wa?(a.W=d,a.H=!0,a.Va(),a.H=!1):a.A=self.setTimeout(a.mc,Math.max(m-l,4))}}wb(){this.D("pointermove",
this.ta);this.ta=null}S(a,d){for(let l=0,m=d.changedTouches.length;l<m;++l){const p=d.changedTouches[l];x(this,a,{pointerId:p.identifier,pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:p.clientX,clientY:p.clientY,pageX:p.pageX,pageY:p.pageY,width:2*(p.radiusX||p.webkitRadiusX||0),height:2*(p.radiusY||p.webkitRadiusY||0),pressure:p.force||p.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:p.rotationAngle||0,timeStamp:d.timeStamp},e)}}ha(a){window!==window.top&&window.focus();
this.Na(a.target)&&document.activeElement&&!this.Na(document.activeElement)&&document.activeElement.blur()}Na(a){return!a||a===document||a===window||a===document.body||"canvas"===a.tagName.toLowerCase()}pb(){this.Ua||(this.Ua=!0,window.addEventListener("deviceorientation",a=>this.Jb(a)),window.addEventListener("deviceorientationabsolute",a=>this.Kb(a)))}ob(){this.Ta||(this.Ta=!0,window.addEventListener("devicemotion",a=>this.Ib(a)))}Jb(a){u(this,"deviceorientation",{absolute:!!a.absolute,alpha:a.alpha||
0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp,webkitCompassHeading:a.webkitCompassHeading,webkitCompassAccuracy:a.webkitCompassAccuracy},e)}Kb(a){u(this,"deviceorientationabsolute",{absolute:!!a.absolute,alpha:a.alpha||0,beta:a.beta||0,gamma:a.gamma||0,timeStamp:a.timeStamp},e)}Ib(a){let d=null;var l=a.acceleration;l&&(d={x:l.x||0,y:l.y||0,z:l.z||0});l=null;var m=a.accelerationIncludingGravity;m&&(l={x:m.x||0,y:m.y||0,z:m.z||0});m=null;const p=a.rotationRate;p&&(m={alpha:p.alpha||0,beta:p.beta||
0,gamma:p.gamma||0});u(this,"devicemotion",{acceleration:d,accelerationIncludingGravity:l,rotationRate:m,interval:a.interval,timeStamp:a.timeStamp},e)}Xb(a){const d=this.c,l=d.h;l.style.width=a.styleWidth+"px";l.style.height=a.styleHeight+"px";l.style.marginLeft=a.marginLeft+"px";l.style.marginTop=a.marginTop+"px";d.Ga();this.Ya&&(l.style.display="",this.Ya=!1)}Nb(a){const d=a.url;a=a.filename;const l=document.createElement("a"),m=document.body;l.textContent=a;l.href=d;l.download=a;m.appendChild(l);
l.click();m.removeChild(l)}async Sb(a){var d=a.imageBitmapOpts;a=await self.C3_RasterSvgImageBlob(a.blob,a.imageWidth,a.imageHeight,a.surfaceWidth,a.surfaceHeight);d=d?await createImageBitmap(a,d):await createImageBitmap(a);return{imageBitmap:d,transferables:[d]}}async Mb(a){return await self.C3_GetSvgImageSize(a.blob)}async Db(a){await T(a.url)}pa(){var a=[...this.va];this.va.clear();if(!this.fc)for(const d of a)(a=d.play())&&a.catch(()=>{this.ic.has(d)||this.va.add(d)})}Hb(a){if(a.show){this.j||
(this.j=document.createElement("div"),this.j.id="inspectOutline",document.body.appendChild(this.j));var d=this.j;d.style.display="";d.style.left=a.left-1+"px";d.style.top=a.top-1+"px";d.style.width=a.width+2+"px";d.style.height=a.height+2+"px";d.textContent=a.name}else this.j&&(this.j.style.display="none")}Tb(){window.C3_RegisterSW&&window.C3_RegisterSW()}Qa(a){window.c3_postToMessagePort&&(a.from="runtime",window.c3_postToMessagePort(a))}Cb(a,d){return this.c.kb(this.G,{name:a,params:d})}ia(a){alert(a.message)}})}"use strict";
{const f=document.currentScript.src;self.jb=class{constructor(c){this.Y=c;this.g=f?f.substr(0,f.lastIndexOf("/")+1):c.g;this.hc=Math.min(navigator.hardwareConcurrency||2,16);this.ra=null;this.$a=[];this.wa=this.sa=null}async ib(){if(this.dc)throw Error("already initialised");this.dc=!0;var c=this.Y.ga("dispatchworker.js");this.ra=await this.Y.Z(c,this.g,{name:"DispatchWorker"});c=new MessageChannel;this.sa=c.port1;this.ra.postMessage({type:"_init","in-port":c.port2},[c.port2]);this.wa=await this.Ia()}async Ia(){const c=
this.$a.length;var e=this.Y.ga("jobworker.js");e=await this.Y.Z(e,this.g,{name:"JobWorker"+c});const g=new MessageChannel,t=new MessageChannel;this.ra.postMessage({type:"_addJobWorker",port:g.port1},[g.port1]);e.postMessage({type:"init",number:c,"dispatch-port":g.port2,"output-port":t.port2},[g.port2,t.port2]);this.$a.push(e);return t.port1}gb(){return{inputPort:this.sa,outputPort:this.wa,maxNumWorkers:this.hc}}hb(){return[this.sa,this.wa]}}}"use strict";
window.C3_IsSupported&&(window.c3_runtimeInterface=new self.o({uc:!1,vc:"workermain.js",B:["scripts/c3runtime.js"],rc:"scripts/",Ba:[],cb:"html5"}));"use strict";
async function ba(){const f=[],c=[];if(navigator.mediaDevices&&navigator.mediaDevices.enumerateDevices){var e=await navigator.mediaDevices.enumerateDevices();for(const g of e){e=g.kind;const t={deviceId:g.deviceId,label:g.label,facing:g.facing||g.facingMode||""};"video"===e||"videoinput"===e?f.push(t):("audio"===e||"audioinput"===e)&&c.push(t)}}return{videoSources:f,audioSources:c}}
async function ca(f,c,e){try{const g=f.c;"object"===typeof e.constraints.audio?await g.ea("CAMERA","RECORD_AUDIO","MODIFY_AUDIO_SETTINGS"):await g.ea("CAMERA");f.l=await navigator.mediaDevices.getUserMedia(e.constraints);c.srcObject=f.l;c.play();f.Za&&!f.Xa&&(f.c.nb(f.lc),f.Xa=!0);return{ok:!0}}catch(g){return console.warn("Error requesting camera: ",g),{ok:!1}}}
async function da(f,c){try{return await f.c.ea("RECORD_AUDIO","MODIFY_AUDIO_SETTINGS"),f.l=await navigator.mediaDevices.getUserMedia(c.constraints),self.C3Audio_OnMicrophoneStream&&self.C3Audio_OnMicrophoneStream(f.l,c.tag),{ok:!0}}catch(e){return console.warn("Error requesting microphone: ",e),{ok:!1}}}
async function ea(f,c){const e=document.createElement("canvas");e.width=f.videoWidth;e.height=f.videoHeight;e.getContext("2d").drawImage(f,0,0,f.videoWidth,f.videoHeight);return{snapshotUrl:await fa(e,c.format,c.quality)}}function V(f,c){f.l===c&&(f.l=null);f=c.getTracks();for(let e=0,g=f.length;e<g;++e)f[e].stop()}function fa(f,c,e){return new Promise(g=>{f.toBlob?f.toBlob(t=>g(URL.createObjectURL(t)),c,e):g(f.toDataURL(c,e))})}
self.o.C(class extends self.${constructor(f){super(f,"user-media");this.F=!1;this.Za=this.c.m;this.kc=0;this.l=null;z(this,"get-media-sources",()=>ba());E(this,"request-camera",(c,e)=>ca(this,c,e));E(this,"request-microphone",(c,e)=>da(this,e));E(this,"snapshot",(c,e)=>ea(c,e));E(this,"stop",c=>{c.srcObject&&(V(this,c.srcObject),c.srcObject=null)});self.C3UserMedia_GetVideoElement=c=>this.f.get(c);self.C3UserMedia_GetLastMediaStream=()=>this.l}N(f){const c=document.createElement("video");c.crossOrigin=
"anonymous";c.autoplay=!0;c.muted=!0;c.playsInline=!0;c.addEventListener("canplaythrough",()=>{D(this,"video-ready",f,{width:c.videoWidth,height:c.videoHeight})});return c}s(){}Fa(f){f.srcObject&&(V(this,f.srcObject),f.srcObject=null)}Ha(){if(this.Za){var f={},c={sequenceNumber:this.kc++,videoData:f},e=[],g=[];for(const [t,r]of this.f.entries()){if(!r.srcObject)continue;const v={};g.push(createImageBitmap(r).then(a=>{v.imageBitmap=a;e.push(a)}).catch(()=>{v.imageBitmap=null}));f[t.toString()]=v}Promise.all(g).then(()=>
u(this,"state",c,!1,e))}}});"use strict";function W(f){f.stopPropagation()}
self.o.C(class extends self.${constructor(f){super(f,"button")}N(f,c){const e=document.createElement("input");var g=e;c.isCheckbox?(e.type="checkbox",g=document.createElement("label"),g.appendChild(e),g.appendChild(document.createTextNode("")),g.style.fontFamily="sans-serif",g.style.userSelect="none",g.style.webkitUserSelect="none",g.style.display="inline-block",g.style.color="black"):e.type="button";g.style.position="absolute";g.addEventListener("touchstart",W);g.addEventListener("touchmove",W);
g.addEventListener("touchend",W);g.addEventListener("mousedown",W);g.addEventListener("mouseup",W);g.addEventListener("keydown",W);g.addEventListener("keyup",W);e.addEventListener("click",()=>F(this,"click",f,{isChecked:e.checked}));c.id&&(e.id=c.id);this.s(g,c);return g}s(f,c){const e="input"===f.tagName.toLowerCase()?f:f.firstChild;e.checked=c.isChecked;e.disabled=!c.isEnabled;f.title=c.title;f===e?e.value=c.text:f.lastChild.textContent=c.text}});"use strict";
function ha(f){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(c=>u(f,"sw-message",c.data))}
function ia(f){f=f.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(f).catch(c=>console.warn("[Construct 3] Failed to lock orientation: ",c));else try{let c=!1;screen.lockOrientation?c=screen.lockOrientation(f):screen.webkitLockOrientation?c=screen.webkitLockOrientation(f):screen.mozLockOrientation?c=screen.mozLockOrientation(f):screen.msLockOrientation&&(c=screen.msLockOrientation(f));c||console.warn("[Construct 3] Failed to lock orientation")}catch(c){console.warn("[Construct 3] Failed to lock orientation: ",
c)}}
self.o.C(class extends self.aa{constructor(f){super(f,"browser");this.b="";B(this,[["get-initial-state",c=>{this.b=c.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>ha(this)],
["alert",c=>this.ia(c)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",c=>this.na(c)],["vibrate",c=>{navigator.vibrate&&navigator.vibrate(c.pattern)}],["lock-orientation",c=>ia(c)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():
screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(c){}}],["navigate",c=>{var e=c.type;if("back"===e)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.back();else if("forward"===e)window.forward();else if("home"===e)window.home();else if("reload"===e)location.reload();else if("url"===e){e=c.url;var g=c.target;c=c.exportType;"windows-uwp"===c&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(e)):
self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(e,"_system"):"preview"===c?window.open(e,"_blank"):this.zc||(2===g?window.top.location=e:1===g?window.parent.location=e:window.location=e)}else"new-window"===e&&(e=c.url,g=c.tag,"windows-uwp"===c.exportType&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(e)):self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(e,"_system"):window.open(e,g))}],["request-fullscreen",
c=>{{const e={navigationUI:"auto"};c=c.navUI;1===c?e.navigationUI="hide":2===c&&(e.navigationUI="show");c=document.documentElement;c.requestFullscreen?c.requestFullscreen(e):c.mozRequestFullScreen?c.mozRequestFullScreen(e):c.msRequestFullscreen?c.msRequestFullscreen(e):c.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?c.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):c.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{document.exitFullscreen?document.exitFullscreen():
document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",c=>{location.hash=c.hash}]]);window.addEventListener("online",()=>{u(this,"online-state",{isOnline:!0})});window.addEventListener("offline",()=>{u(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{u(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",
()=>{u(this,"backbutton")});"undefined"!==typeof Windows&&Windows.UI.Core.SystemNavigationManager.getForCurrentView().addEventListener("backrequested",c=>{c.handled=!0;u(this,"backbutton")})}ia(f){alert(f.message)}na(f){f=f.isFocus;if("nwjs"===this.b){const c="nwjs"===this.b?nw.Window.get():null;f?c.focus():c.blur()}else f?window.focus():window.blur()}});"use strict";function X(f){f.stopPropagation()}function Y(f){const c=document.createElement("option");c.text=f;return c}
function Z(f){const c=f.selectedIndex,e=[];for(let g=0,t=f.length;g<t;++g)f.options[g].selected&&e.push(g);return{selectedIndex:c,selectedIndices:e}}
self.o.C(class extends self.${constructor(f){super(f,"list");E(this,"set-selected-index",(c,e)=>{c.selectedIndex=e.selectedIndex});E(this,"add-item",(c,e)=>{{const g=e.index;e=Y(e.text);0>g?c.add(e):c.add(e,g)}});E(this,"remove-item",(c,e)=>{c.remove(e.index)});E(this,"set-item",(c,e)=>{c.options[e.index].text=e.text});E(this,"clear",c=>{c.innerHTML=""});E(this,"load-state",(c,e)=>{c.innerHTML="";for(const g of e.items)c.add(Y(g));c.selectedIndex=e.selectedIndex;for(const g of e.selectedIndices)if(e=
c.options[g])e.selected=!0})}N(f,c){const e=c.isDropdown,g=c.isMultiSelect,t=c.items,r=document.createElement("select");r.style.position="absolute";r.style.userSelect="none";r.style.webkitUserSelect="none";r.multiple=g;e||(r.size=2);for(const v of t)r.add(Y(v));r.addEventListener("touchstart",X);r.addEventListener("touchmove",X);r.addEventListener("touchend",X);r.addEventListener("mousedown",X);r.addEventListener("mouseup",X);r.addEventListener("click",v=>{v.stopPropagation();F(this,"click",f,Z(r))});
r.addEventListener("dblclick",v=>{v.stopPropagation();F(this,"dblclick",f,Z(r))});r.addEventListener("change",()=>D(this,"change",f,Z(r)));c.id&&(r.id=c.id);this.s(r,c);return r}s(f,c){f.title=c.title;f.disabled=!c.isEnabled;f.multiple=!!c.isMultiSelect}});